### ISSUE TITLE
How to checkout gorilla

### ISSUE THREAD

**Issue by iaGuoZhi** [hipdac-lab/FCBench#1]
FCBench doesn't have a gorilla branch as well as influxdb

**Comment by xinyu2** [comment]
This is a git submodule issue.  We will fix this soon.  Please use the following steps as an walk-around method at this time.
1) clone https://github.com/panagiotisl/influxdb.git to $You-code-directory/influxdb
2) copy FCBench/influxdb/tsdb/engine/tsm1/compress_test.go $You-code-directory/influxdb/tsdb/engine/tsm1
3) git checkout chimp128 (or gorilla) for testing

**Comment by iaGuoZhi** [comment]
That would be helpful, thanks!

**Comment by aabduvakhobov** [comment]
I can't find `FCBench/influxdb/tsdb/engine/tsm1/compress_test.go` in this directory.
